In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
X = np.array([1,2,3,5])
y = np.array([3,5,7,11])

In [4]:
model = LinearRegression()
model.fit(X, y)

ValueError: Expected 2D array, got 1D array instead:
array=[1 2 3 5].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [5]:
X = X[..., np.newaxis] # X.reshape(-1, 1)
X.shape

(4, 1)

In [6]:
X

array([[1],
       [2],
       [3],
       [5]])

In [7]:
model.fit(X, y)

LinearRegression()

In [8]:
for_predict = np.array([[4],
                        [6]])

for_predict.shape

(2, 1)

In [9]:
model.predict(for_predict)

array([ 9., 13.])

In [10]:
# W : coef_
# b : intercept_

model.coef_

array([2.])

In [11]:
model.intercept_

1.0000000000000009

In [12]:
c = np.arange(1, 20)
f = c * 1.8 + 32

In [13]:
model = LinearRegression()
model.fit(c.reshape(-1, 1), f)

LinearRegression()

In [14]:
model.predict(np.array([[30]]))

array([86.])

In [15]:
model.coef_

array([1.8])

In [16]:
model.intercept_

31.999999999999993

- 데이터 스케일링의 사본

In [17]:
import pandas as pd
movie_score = pd.DataFrame({
    "naver":[0, 2, 4, 6, 8],
    "netflix":[1, 2, 3, 4, 5]
})

movie_score

naver  netflix
0      0        1
1      2        2
2      4        3
3      6        4
4      8        5

In [18]:
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()

In [19]:
movie_score_scalered = min_max_scaler.fit_transform(movie_score)

pd.DataFrame(movie_score_scalered, columns=["Naver Scaled", "Netflix Scaled"])

Naver Scaled  Netflix Scaled
0          0.00            0.00
1          0.25            0.25
2          0.50            0.50
3          0.75            0.75
4          1.00            1.00

In [20]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()

In [21]:
import numpy as np
x = np.arange(10)
# 이상치 강제 추가
x[9] = 1000

In [22]:
x.mean(), x.std()

(103.6, 298.8100399919654)

In [23]:
std_scaled_x = std_scaler.fit_transform(x.reshape(-1,1))
std_scaled_x.mean(), std_scaled_x.std()

(4.4408920985006264e-17, 1.0)

In [ ]:
std_scaled_x

In [24]:
# 불필요한 경고 출력 방지
import warnings

warnings.filterwarnings('ignore')

In [25]:
# iris 데이터셋 로딩
from sklearn.datasets import load_iris
iris = load_iris()

In [ ]:
print(iris['DESCR'])

In [26]:
data = iris['data']
data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [27]:
feature_names = iris["feature_names"]
feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [28]:
target = iris['target']
target[:5]

array([0, 0, 0, 0, 0])

In [29]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [30]:
import pandas as pd

df_iris = pd.DataFrame(
    iris['data'],
    columns=iris['feature_names']
)

df_iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2