In [24]:
import numpy as np


In [25]:
# 행 슬라이싱, 열 슬라이싱
# 4, 5


In [26]:
np.random.randn(10).reshape(2,5).round(4)

array([[-0.8792,  0.4278, -0.1261, -0.0941, -0.7003],
       [ 1.3216, -0.0515, -0.5338,  1.1993,  0.2203]])

In [27]:
np.random.binomial(10, 0.5, 20).reshape(-1,5).round(4)

array([[2, 5, 5, 4, 5],
       [3, 5, 5, 8, 4],
       [4, 1, 4, 6, 2],
       [4, 4, 7, 3, 3]])

In [28]:
a = np.arange(1,13).reshape(3,-1)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
a = np.array([42,38,12,25])

In [30]:
# 오름차순(ascending order)
np.sort(a)

array([12, 25, 38, 42])

In [31]:
#a의 사본이 만들어진다.

In [32]:
# 내림차순(descending order)
np.sort(a)[::-1] # 시작부터 끝까지 -1은 역순

array([42, 38, 25, 12])

In [33]:
# 참고사항 - Palindrome


In [34]:
# madam, 소주만병만주소 -> 정, 역방향이 똑같다. 

In [35]:
def is_palindrome(s):

    """Check whether a string is a palindrome"""
    return s== s[::-1]
# s가 palindrome 이면 true, 아니면 false를 반환하는 함수

    

In [36]:
# a = np.array([42,38,12,25])

# 12, 25, 38, 42 - 12는 index2, 25는 3 38은 1 42은 0
np.argsort(a)

array([2, 3, 1, 0], dtype=int64)

In [37]:
index = np.argsort(a)
a[index]

array([12, 25, 38, 42])

In [38]:
a[[2,3,1,0]]   # fancy index

array([12, 25, 38, 42])

In [39]:
a[[1,2]]

array([38, 12])

In [40]:
# 자기파괴적 메소드 , inplace mode
a

array([42, 38, 12, 25])

In [41]:
a.sort()
a

array([12, 25, 38, 42])

In [22]:
# sigmoid 함수 그리기
import numpy as np
import matplotlib as plt

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

x = np.arange(-5.0,5.0,0.1)
y = sigmoid(x)
plt.plot(x, y)
plt.ylim(-0.1, 1.1)
plt.show()

AttributeError: module 'matplotlib' has no attribute 'plot'

In [23]:
xs = np.linspace(-3,3,601)
sigmoid = 1 / 1+ (np.exp(-xs))
plt.plot(xs, sigmoid)
plt.yticks([0,0.5,1])
plt.grid()
plt.title('Sigmoid graph')
plt.show()

AttributeError: module 'matplotlib' has no attribute 'plot'

In [42]:
# Array operation
# - Array operation

In [43]:
a = np.random.randint(1,10, 6).reshape(2,3)
b = np.random.randint(1,10, 6).reshape(2,3)

In [44]:
b

array([[8, 7, 9],
       [5, 4, 1]])

In [45]:
a 

array([[9, 8, 1],
       [3, 5, 8]])

In [47]:
a + b

array([[17, 15, 10],
       [ 8,  9,  9]])

In [48]:
a - a

array([[0, 0, 0],
       [0, 0, 0]])

In [49]:
a * a

array([[81, 64,  1],
       [ 9, 25, 64]])

In [50]:
a/a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [51]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
# Transpose
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [53]:
# dot product
np.dot(a, a.T)


array([[14, 32],
       [32, 77]])

# dot product가 왜 필요한지?
- y = wx +b -> wx안에 들어가는게 dot product
- gpu가 dot product의 연산등을 해준다.

In [54]:
a.dot(a.T)

array([[14, 32],
       [32, 77]])

In [55]:
# Broadcasting
a * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [56]:
# All & Any -> 그냥 넘어감


In [57]:
# boolean index -> 다른 말로는 필터링이라고 함
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [58]:
a > 3

array([False, False, False, False,  True,  True,  True,  True])

In [59]:
# filtering -> 시리즈에서 밑에 식을 사용할 수 있어서 중요(매우 많이 사용)

a[a >3]

array([4, 5, 6, 7])

In [67]:
import pandas as pd
df = pd.DataFrame(np.arange(16).reshape(4,4), columns= list('ABCD'))
df


A   B   C   D
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [63]:
df.B[df.B > 8]

2     9
3    13
Name: B, dtype: int32

In [64]:
df[df.B >8]

A   B   C   D
2   8   9  10  11
3  12  13  14  15

In [70]:
df[(df.B > 4 )& (df.B <10)]  # -> 괄호로 묶어서 사용

A  B   C   D
1  4  5   6   7
2  8  9  10  11

In [74]:
df[(df.B < 4) | (df.B > 10)] # shift + 백슬러시

A   B   C   D
0   0   1   2   3
3  12  13  14  15

In [72]:
# Fancy index
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [73]:
a[[-1,-2,-3]]

array([7, 6, 5])

#연습문제


In [ ]:
문제1. 행렬만들기

In [98]:
np.arange(10,81,10).reshape(2,4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [99]:
np.arange(1,9).reshape(2,4)*10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [76]:
# 내가 한거
C = [(10,20,30,40,50,60,70,80)]
C

[(10, 20, 30, 40, 50, 60, 70, 80)]

문제 2. indexing, slicing

In [82]:
m = np.array([[0,1,2,3,4], 
             [5,6,7,8,9],
             [10,11,12,13,14]])

m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [83]:
m[1,2]

7

In [84]:
m[2,-1]

14

In [85]:
m[1,1:3]

array([6, 7])

In [86]:
m[1:3,2]

array([ 7, 12])

In [100]:
m[:2,3:]

array([[3, 4],
       [8, 9]])

문제3. boolean indexing

In [102]:
f = m.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [97]:
n3 =int(input(" 배수를 입력하세요. 배수"))
for i in m1:
    if i%n3 ==0:
        print(i, end =" " )

KeyboardInterrupt: Interrupted by user

In [103]:
# 3의 배수
f[f % 3==0]


array([ 0,  3,  6,  9, 12])

In [104]:
# 4로 나누면 1이 남는 수
f[f % 4 == 1]

array([ 1,  5,  9, 13])

In [105]:
# 위 두개의 집합
f[np.logical_and(f % 3==0, f % 4 == 1)]

array([9])

In [106]:
f[(f % 3==0) & (f % 4 == 1)]

array([9])

문제 4. 대각선 행렬


In [109]:
np.eye(5,5,-1,int)*3 +np.eye(5,5,0,int)*2 +np.eye(5,5,1,int)

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

문제 5. Matrix operation

In [110]:

np.random.seed(2021)
a = np.random.uniform(0,10,30).reshape(5,6).round(4)
a

array([[6.0598, 7.3337, 1.3895, 3.1267, 9.9724, 1.2816],
       [1.7899, 7.5293, 6.6216, 7.8431, 0.9689, 0.5857],
       [9.624 , 6.1656, 0.8663, 5.6127, 6.1652, 9.6384],
       [5.743 , 3.7116, 4.5215, 2.0185, 5.6931, 1.951 ],
       [5.837 , 4.7631, 5.1781, 8.231 , 7.3223, 0.6906]])

In [112]:
# 전체의 최대값
a.max()

9.9724

In [113]:
# 각 행의 합
np.sum(a, axis = 1)

array([29.1637, 25.3385, 38.0722, 23.6387, 32.0221])

In [114]:
# 각 행의 최댓값
np.max(a, axis=1)

array([9.9724, 7.8431, 9.6384, 5.743 , 8.231 ])

In [115]:
a.max(axis=1)

array([9.9724, 7.8431, 9.6384, 5.743 , 8.231 ])

In [116]:
# 각 열의 평균
np.mean(a, axis =0)

array([5.81074, 5.90066, 3.7154 , 5.3664 , 6.02438, 2.82946])

In [117]:
# 각 열의 최소값
np.min(a, axis =0)

array([1.7899, 3.7116, 0.8663, 2.0185, 0.9689, 0.5857])

문제6. Sorting


In [119]:
score = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [120]:
# 영어 성적 정렬
np.sort(score[1])

array([ 46,  71,  99, 100])

In [121]:
# 영어 성적 내림차순 정렬
np.sort(score[1])[::-1]

array([100,  99,  71,  46])

In [122]:
# 영어 성적 내림차순의 Index값
indices = np.argsort(score[1])[::-1]
indices

array([2, 1, 3, 0], dtype=int64)

In [123]:
# 모든 행을 영어성적 내림차순 기준으로 정렬
score[:, indices]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [124]:
# 한 줄로 표현
score[:, np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

문제 7. 주사위 100번


In [125]:
np.random.seed(2021)
dice = np.random.randint(1,7,100)
dice

array([5, 6, 2, 1, 6, 5, 4, 6, 6, 6, 1, 5, 2, 6, 2, 2, 5, 6, 3, 3, 1, 4,
       2, 1, 3, 4, 5, 6, 1, 6, 2, 3, 6, 2, 6, 2, 3, 3, 5, 6, 3, 4, 2, 3,
       3, 1, 3, 5, 6, 4, 4, 2, 2, 2, 3, 6, 4, 4, 5, 4, 2, 5, 2, 2, 5, 4,
       6, 4, 4, 4, 3, 2, 4, 3, 6, 3, 3, 1, 5, 4, 2, 4, 2, 5, 3, 4, 2, 3,
       6, 3, 6, 3, 4, 5, 6, 2, 2, 6, 1, 6])

In [126]:
np.mean(dice)

3.7

In [127]:
np.unique(dice, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([ 8, 21, 19, 18, 13, 21], dtype=int64))

In [129]:
 # (array([1, 2, 3, 4, 5, 6])-> 유니크 array([ 8, 21, 19, 18, 13, 21] ->counts
# 위에껄 딕셔너리로
unique, counts = np.unique(dice, return_counts=True)
dict(zip(unique, counts))

{1: 8, 2: 21, 3: 19, 4: 18, 5: 13, 6: 21}

In [130]:
import pandas as pd
s = pd.Series(counts, index= unique) # 데이터프레임 시리즈
s

1     8
2    21
3    19
4    18
5    13
6    21
dtype: int64

문제 8.

In [137]:
# 5개만 먼저 테스트
import numpy as np
np.random.seed(2021)
rate = np.random.randn(5) * 0.01
rate

array([ 0.01488609,  0.00676011, -0.00418451, -0.00806521,  0.00555876])

In [139]:
price = 10000
for i in range(5):
    price += price * rate[i]  # price = price * (1+rate[i])
    price = np.round(price)
    print(price, end =' ')

10149.0 10218.0 10175.0 10093.0 10149.0 

In [141]:
#250개
import numpy as np
np.random.seed(2021)
rate = np.random.randn(250) * 0.01
price_list = [10000]
for i in range(250):
    price = price_list[i] * (1 + rate[i])  # price = price * (1+rate[i])
    price = np.round(price)
    price_list.append(int(price))


price_list[:10]

[10000, 10149, 10218, 10175, 10093, 10149, 10077, 10191, 10257, 10268]

In [142]:
len(price_list)

251

In [145]:
# 똑같은 로직을 empty를 써서 만들어 봄
np.random.seed(2021)
rate = np.random.randn(250) * 0.01
price_array = np.empty(251, int)
price_array[0] =10000
for i in range(250):
    price = price_array[i] * (1 + rate[i])  # price = price * (1+rate[i])
    price = np.round(price)
    price_array[i+1] = int(price)
    


price_array[:10]

array([10000, 10149, 10218, 10175, 10093, 10149, 10077, 10191, 10257,
       10268])

In [146]:
# array는 한번 지정되면 크기가 고정되어있는거
# list 는 크기가 가변적이고 , 속도가 느리다.

#정수
# int 16bit
# int 32bit -2147483648 ~2147483648 2의 31승수  # 디폴트값
# long 64bit

# 실수
# double 64   # 디폴트값
# single 32

In [148]:
np.array([1,2,3,4], dtype = np.int64)

array([1, 2, 3, 4], dtype=int64)


# pandas
- 열과 행으로 구성된 테이블 형태의 데이터를 다루는데 주로 사용
- 테이블 형태 = 엑셀 형태 ( 피벗 테이블(중요)) , DBMS( join, group by)
